### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by SheepCommander** [jaydensar/tray-status-picker#2]
I'm assuming it's abandoned, but just to make sure

![image](https://user-images.githubusercontent.com/66646514/144536444-539780cd-1b97-4f1f-907c-3fb3aa43333a.png)

Potential issue: I _am_ on win11 which might change things, but the [Reload from tray plugin](https://github.com/D-Brox/reload-from-tray) still works fine for me

**Comment by jaydns** [comment]
This plugin is incompatible with Reload from tray, as they both use the same methods for setting to the tray and override each other. See Reload from tray's README:

![](https://i.jaydensar.net/2021/12/32a0b5db-cb85-45bb-912c-ad5581cb9a33.png)

**Comment by SheepCommander** [comment]
Ohhhh I didn't realize, sorry for not reading. Thanks
